# Project language
language: php

# Start mariadb service
services:
- postgresql

# Cache composer packages so "composer install" is faster
cache:
  directories:
  - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.1
  - php: 7.2
  - php: hhvm
  allow_failures:
  - php: hhvm


# Install composer dependencies,
install:
- phpenv config-add travis.php.ini
- composer self-update
- composer install


# After a build, send email notification with the build results
notifications:
  email:
    recipients:
    - walid_mohsin10@hotmail.com
    on_success: never
